# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['run.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('app/themes/*.qss', 'app/themes'),
        ('app/assets/*.ico', 'app/assets'),
        ('app/config/*.json', 'app/config'),
        ('app/plugins/*.py', 'app/plugins'),
    ],
    hiddenimports=[
        'PyQt6.QtCore',
        'PyQt6.QtGui', 
        'PyQt6.QtWidgets',
        'PyQt6.QtNetwork',
        'win32api',
        'win32con',
        'win32gui',
        'win32process',
        'psutil',
        'keyboard',
        'scapy',
        'scapy.all',
        'scapy.layers.inet',
        'scapy.layers.l2',
        'threading',
        'subprocess',
        'socket',
        'json',
        'logging',
        'datetime',
        'time',
        'os',
        'sys',
        'ctypes',
        'ctypes.wintypes',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='PulseDropPro',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # icon='app/assets/icon.ico',  # Commented out due to icon format issues
    version='file_version_info.txt',
    uac_admin=True,
)
