# app/__version__.py — single source of truth for DupeZ's runtime version.
#
# Bump this alongside:
#   - packaging/version_info.py      (PyInstaller VS_VERSION_INFO resource)
#   - packaging/dupez.manifest       (Windows assemblyIdentity version)
#   - packaging/dupez_compat.manifest
#   - packaging/installer.iss        (Inno Setup #define MyAppVersion)
#   - packaging/build.bat            (DUPEZ_VERSION env var)
#   - packaging/build_variants.bat   (DUPEZ_VERSION env var)
#   - README.md                      (title header, release asset filename)
#   - CHANGELOG.md                   (new version section)
#   - ROADMAP.md                     (Completed section entry)
#
# packaging/build_variants.bat is the canonical release driver
# (dual-variant GPU + Compat build). These files are kept in lockstep by
# convention — there is no autogenerated sync step.
#
# Anything that needs the current runtime version at Python level (window
# title, User-Agent header, update checker baseline, telemetry, logs)
# MUST import __version__ from this module. Do NOT hardcode version
# strings anywhere else in app/.

__version__ = "5.3.0"
