# app/firewall_helper/auth.py
"""
Helper IPC mutual authentication (ADR-0001 §6 — shared-secret handshake).

Threat model
------------
The helper pipe SECURITY_ATTRIBUTES DACL intentionally grants GenericAll
to Everyone + Authenticated Users so a Medium-IL GUI can drive the
High-IL helper. Without authentication, ANY Medium-IL process on the
same interactive session (browser extension, rogue user-space malware,
another app running as the same user) can:

    1. Open the named pipe.
    2. Send ALLOWED_OPS — including OP_SHUTDOWN or OP_DISRUPT_DEVICE.
    3. Drive WinDivert + netsh operations at High IL.

That's a local-privilege-escalation pipe. The only thing the DACL
accomplishes by itself is keeping network clients out (we separately
use PIPE_REJECT_REMOTE_CLIENTS for that).

Mitigation
----------
A cryptographic mutual handshake MUST complete before ANY opcode in
ALLOWED_OPS is dispatched. The handshake binds both sides to a 32-byte
shared secret that is known only to the parent GUI that spawned this
specific helper instance and to the helper itself.

Protocol (over the existing LF-framed JSON wire, before any Request):

    C --> S   {"type":"client_hello","nonce":<hex>,"version":1}
    C <-- S   {"type":"server_hello","nonce":<hex>,"proof":<hex>}
                where proof = HMAC-SHA256(secret, b"S"||c_nonce||s_nonce)
    C --> S   {"type":"client_proof","proof":<hex>}
                where proof = HMAC-SHA256(secret, b"C"||c_nonce||s_nonce)
    C <-- S   {"type":"handshake_ok"}                            (or close)

Properties
----------
* Bidirectional: client verifies server's proof AND server verifies
  client's proof — a rogue server on the same pipe can't fool the
  client, a rogue client can't fool the server.
* Replay-resistant: both proofs bind to BOTH nonces, so replaying a
  captured transcript against a fresh handshake fails.
* Constant-time comparisons everywhere (``hmac.compare_digest``).
* Bounded: handshake must complete within HANDSHAKE_TIMEOUT_SEC or the
  server disconnects. No unauthenticated frames are dispatched.

Secret transport
----------------
The 32-byte secret is generated by the parent GUI and written to a
user-private sentinel file inside ``%LOCALAPPDATA%\\DupeZ\\helper_auth.tok``
before the helper is spawned. The helper reads the sentinel on startup,
keeps the bytes in memory, and deletes the sentinel from disk so it
cannot be later stolen by the same user's other processes. Sentinel
lifetime on disk is ≤ a few seconds in normal operation.

Rationale vs. alternatives
--------------------------
* Environment variables — don't cross ShellExecuteEx("runas") reliably
  on every Windows version and leak via WMI enumeration.
* Command-line argument — visible to ``tasklist /v`` and WMI Win32_Process.
* Named-pipe client-SID check (via GetNamedPipeClientProcessId) — works
  for user identity but any same-user process still passes, so it does
  NOT solve the stated threat.
* Windows DPAPI-encrypted token — overkill for an ephemeral secret that
  exists only for the lifetime of a single helper launch.
"""

from __future__ import annotations

import hmac
import json
import logging
import os
import secrets
from hashlib import sha256
from pathlib import Path
from typing import Optional

__all__ = [
    "HANDSHAKE_TIMEOUT_SEC",
    "AuthenticationError",
    "HandshakeError",
    "compute_client_proof",
    "compute_server_proof",
    "generate_token",
    "handshake_server",
    "handshake_client",
    "token_sentinel_path",
    "write_token_sentinel",
    "read_and_consume_token_sentinel",
]

log = logging.getLogger(__name__)

# ── Constants ─────────────────────────────────────────────────────────

TOKEN_BYTES = 32                 # 256-bit shared secret (HMAC key)
NONCE_BYTES = 32                 # per-handshake nonce
HANDSHAKE_VERSION = 1
HANDSHAKE_TIMEOUT_SEC = 3.0      # hard wall-clock budget


# ── Exceptions ────────────────────────────────────────────────────────

class AuthenticationError(RuntimeError):
    """Raised when a peer fails the mutual handshake."""


class HandshakeError(RuntimeError):
    """Raised on malformed / timed-out handshake frames (pre-auth)."""


# ── Token generation ─────────────────────────────────────────────────

def generate_token() -> bytes:
    """Return a fresh 32-byte secret from the OS CSPRNG."""
    return secrets.token_bytes(TOKEN_BYTES)


# ── Token sentinel (parent → helper out-of-band channel) ────────────

def token_sentinel_path() -> Path:
    """Path to the user-private sentinel file used to transfer the token.

    LOCALAPPDATA is already user-private on every supported Windows
    version (it lives under the user's profile with inheritance-blocked
    ACLs by default), so no explicit DACL work is needed.
    """
    base = os.environ.get("LOCALAPPDATA") or os.path.expanduser("~")
    return Path(base) / "DupeZ" / "helper_auth.tok"


def write_token_sentinel(token: bytes) -> Path:
    """Write *token* to the sentinel path. Returns the path.

    Creates parent directory if missing. Overwrites any stale token.
    """
    if len(token) != TOKEN_BYTES:
        raise ValueError(f"token must be exactly {TOKEN_BYTES} bytes")
    path = token_sentinel_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    # Write atomically so a concurrent helper start never sees a half file.
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_bytes(token)
    try:
        os.replace(tmp, path)
    except OSError:
        # os.replace should succeed within the same directory on Windows;
        # fall back to simple rename if not.
        tmp.rename(path)
    return path


def read_and_consume_token_sentinel() -> Optional[bytes]:
    """Read the sentinel, delete it, and return the token bytes.

    Returns None if the sentinel is missing or malformed. The caller
    (the helper process) keeps the returned bytes in memory and uses
    them as the HMAC key for every subsequent handshake.

    Sentinel deletion is best-effort: if the file can't be unlinked
    (e.g., AV is holding it), we still return the token so the helper
    can run — but we log a warning so the condition is visible.
    """
    path = token_sentinel_path()
    try:
        data = path.read_bytes()
    except (FileNotFoundError, PermissionError, OSError) as e:
        log.warning("auth sentinel missing/unreadable: %s", e)
        return None

    try:
        path.unlink(missing_ok=True)
    except OSError as e:
        log.warning("could not remove auth sentinel after read: %s", e)

    if len(data) != TOKEN_BYTES:
        log.error("auth sentinel has wrong size: %d (expected %d)",
                  len(data), TOKEN_BYTES)
        return None
    return data


# ── Proof computation ────────────────────────────────────────────────

def compute_server_proof(secret: bytes, c_nonce: bytes, s_nonce: bytes) -> bytes:
    """HMAC-SHA256 tag demonstrating the server knows *secret*."""
    return hmac.new(secret, b"S" + c_nonce + s_nonce, sha256).digest()


def compute_client_proof(secret: bytes, c_nonce: bytes, s_nonce: bytes) -> bytes:
    """HMAC-SHA256 tag demonstrating the client knows *secret*."""
    return hmac.new(secret, b"C" + c_nonce + s_nonce, sha256).digest()


# ── Handshake orchestration ─────────────────────────────────────────
#
# The transport is JSON-over-LF. We reuse the same framing as protocol.py
# (short JSON object, LF terminator, ≤ 64 KiB). Callers supply the
# read_frame / write_frame primitives so this module stays free of any
# Windows-specific imports — important for unit testing on Linux.

def _hex(b: bytes) -> str:
    return b.hex()


def _unhex(s: str, expected_len: int, field: str) -> bytes:
    try:
        raw = bytes.fromhex(s)
    except (TypeError, ValueError) as e:
        raise HandshakeError(f"bad hex in {field}: {e}") from e
    if len(raw) != expected_len:
        raise HandshakeError(
            f"{field}: expected {expected_len} bytes, got {len(raw)}"
        )
    return raw


def handshake_server(
    secret: bytes,
    read_frame: callable,
    write_frame: callable,
) -> None:
    """Run the server side of the mutual handshake.

    Raises AuthenticationError on bad client proof; HandshakeError on
    malformed frames or protocol mismatch. Returns normally on success.

    The caller MUST NOT dispatch any subsequent Request until this call
    returns without raising.
    """
    # 1. Read client_hello.
    raw = read_frame()
    if raw is None:
        raise HandshakeError("client disconnected before hello")
    try:
        hello = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as e:
        raise HandshakeError(f"invalid client_hello: {e}") from e
    if not isinstance(hello, dict):
        raise HandshakeError("client_hello not a JSON object")
    if hello.get("type") != "client_hello":
        raise HandshakeError(f"unexpected type: {hello.get('type')!r}")
    if int(hello.get("version", 0)) != HANDSHAKE_VERSION:
        raise HandshakeError(
            f"unsupported handshake version: {hello.get('version')!r}"
        )
    c_nonce = _unhex(hello.get("nonce", ""), NONCE_BYTES, "client nonce")

    # 2. Send server_hello with proof.
    s_nonce = secrets.token_bytes(NONCE_BYTES)
    s_proof = compute_server_proof(secret, c_nonce, s_nonce)
    server_hello = {
        "type": "server_hello",
        "nonce": _hex(s_nonce),
        "proof": _hex(s_proof),
        "version": HANDSHAKE_VERSION,
    }
    write_frame((json.dumps(server_hello, separators=(",", ":")) + "\n").encode("utf-8"))

    # 3. Read client_proof.
    raw = read_frame()
    if raw is None:
        raise HandshakeError("client disconnected after server_hello")
    try:
        cp = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as e:
        raise HandshakeError(f"invalid client_proof: {e}") from e
    if not isinstance(cp, dict) or cp.get("type") != "client_proof":
        raise HandshakeError(f"expected client_proof, got: {cp!r}")
    provided = _unhex(cp.get("proof", ""), sha256().digest_size, "client proof")

    expected = compute_client_proof(secret, c_nonce, s_nonce)
    if not hmac.compare_digest(expected, provided):
        raise AuthenticationError("client proof failed — rejecting connection")

    # 4. Confirm handshake.
    ok = {"type": "handshake_ok"}
    write_frame((json.dumps(ok, separators=(",", ":")) + "\n").encode("utf-8"))


def handshake_client(
    secret: bytes,
    read_frame: callable,
    write_frame: callable,
) -> None:
    """Run the client side of the mutual handshake.

    Raises AuthenticationError if the server proof fails verification;
    HandshakeError on malformed frames.
    """
    # 1. Send client_hello.
    c_nonce = secrets.token_bytes(NONCE_BYTES)
    hello = {
        "type": "client_hello",
        "nonce": _hex(c_nonce),
        "version": HANDSHAKE_VERSION,
    }
    write_frame((json.dumps(hello, separators=(",", ":")) + "\n").encode("utf-8"))

    # 2. Read server_hello.
    raw = read_frame()
    if raw is None:
        raise HandshakeError("server disconnected before server_hello")
    try:
        sh = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as e:
        raise HandshakeError(f"invalid server_hello: {e}") from e
    if not isinstance(sh, dict) or sh.get("type") != "server_hello":
        raise HandshakeError(f"expected server_hello, got: {sh!r}")
    if int(sh.get("version", 0)) != HANDSHAKE_VERSION:
        raise HandshakeError(f"server handshake version mismatch: {sh.get('version')!r}")
    s_nonce = _unhex(sh.get("nonce", ""), NONCE_BYTES, "server nonce")
    s_proof = _unhex(sh.get("proof", ""), sha256().digest_size, "server proof")

    expected = compute_server_proof(secret, c_nonce, s_nonce)
    if not hmac.compare_digest(expected, s_proof):
        raise AuthenticationError(
            "server proof failed — refusing to connect (possible MitM "
            "on the named pipe)"
        )

    # 3. Send client_proof.
    c_proof = compute_client_proof(secret, c_nonce, s_nonce)
    cp = {
        "type": "client_proof",
        "proof": _hex(c_proof),
    }
    write_frame((json.dumps(cp, separators=(",", ":")) + "\n").encode("utf-8"))

    # 4. Read handshake_ok.
    raw = read_frame()
    if raw is None:
        raise HandshakeError("server disconnected before handshake_ok")
    try:
        ok = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as e:
        raise HandshakeError(f"invalid handshake_ok: {e}") from e
    if not isinstance(ok, dict) or ok.get("type") != "handshake_ok":
        raise AuthenticationError(f"handshake did not complete: {ok!r}")
