# build_common.py — Shared PyInstaller Analysis/PYZ/EXE factory used
# by dupez_gpu.spec and dupez_compat.spec.
#
# Two build variants ship from this codebase:
#
#   * DupeZ-GPU.exe   — asInvoker manifest, DUPEZ_ARCH=split default.
#                       GUI runs at Medium IL → Chromium GPU process
#                       works → embedded iZurvive map renders with
#                       hardware raster. Elevated helper process
#                       (dupez_helper.py) is auto-spawned on first
#                       disruption_manager call and owns WinDivert.
#
#   * DupeZ-Compat.exe — requireAdministrator manifest,
#                        DUPEZ_ARCH=inproc default. Single-process
#                        build with WinDivert + netsh running
#                        directly in-process. Chromium GPU refuses
#                        to start under admin token → map falls
#                        through to software raster. Identical to
#                        pre-ADR-0001 shipping builds. For users on
#                        blocklisted GPUs or who cannot tolerate
#                        the helper auto-spawn flow.
#
# Both variants share:
#   * identical hiddenimports
#   * identical datas / binaries (WinDivert DLLs, configs, themes)
#   * identical upx_exclude list (Qt + QtWebEngine DLLs)
#   * identical excludes (torch / whisper / tkinter / etc.)
#
# The only differences are:
#   * compiled-in _BUILD_DEFAULT_ARCH (written by this module before
#     Analysis runs)
#   * EXE name
#   * manifest= path
#   * uac_admin flag
#
# Usage from a .spec file:
#
#     from build_common import build_variant
#     exe = build_variant(
#         variant="gpu",          # or "compat"
#         exe_name="DupeZ-GPU",
#         manifest_path="dupez.manifest",
#         uac_admin=False,
#     )

from __future__ import annotations

import os
import sys

from PyInstaller.building.api import EXE, PYZ
from PyInstaller.building.build_main import Analysis
from PyInstaller.utils.hooks import collect_submodules


# HERE  = the packaging/ dir (this file's own dir). Sibling files like
#         dupez.manifest, dupez_compat.manifest, and version_info.py live
#         here and are resolved relative to HERE.
# ROOT  = the repo root (one level up). Entry points (dupez.py,
#         dupez_helper.py) and the `app/` tree live here and are
#         resolved relative to ROOT. Analysis is invoked with
#         pathex=[ROOT] so PyInstaller can import the app package
#         regardless of the cwd the user runs pyinstaller from.
HERE = os.path.abspath(os.path.dirname(__file__) or ".")
ROOT = os.path.abspath(os.path.join(HERE, ".."))
BLOCK_CIPHER = None


# ── Compiled-in arch default ────────────────────────────────────────

_BUILD_DEFAULT_MODULE = os.path.join(
    ROOT, "app", "firewall_helper", "_build_default.py"
)

_BUILD_DEFAULT_TEMPLATE = '''# app/firewall_helper/_build_default.py
# AUTO-GENERATED BY build_common.py — DO NOT EDIT BY HAND.
#
# This file is (re)written before every PyInstaller build to bake
# the chosen DUPEZ_ARCH default into the frozen exe. feature_flag.py
# imports _BUILD_DEFAULT_ARCH from here; if this file is missing
# (dev run from source), the fallback default is "inproc".

_BUILD_DEFAULT_ARCH = {arch!r}
'''


def _write_build_default(variant: str) -> None:
    """Write ``_build_default.py`` with the right arch for this variant."""
    arch = {"gpu": "split", "compat": "inproc"}.get(variant)
    if arch is None:
        raise ValueError(f"unknown variant {variant!r}; expected gpu or compat")
    os.makedirs(os.path.dirname(_BUILD_DEFAULT_MODULE), exist_ok=True)
    with open(_BUILD_DEFAULT_MODULE, "w", encoding="utf-8") as fh:
        fh.write(_BUILD_DEFAULT_TEMPLATE.format(arch=arch))
    print(
        f"[build_common] wrote {_BUILD_DEFAULT_MODULE} "
        f"(variant={variant}, arch={arch})"
    )


# ── Shared analysis inputs ─────────────────────────────────────────

def _hidden_imports() -> list:
    return (
        collect_submodules("app")
        + [
            # Helper-mode entry point — dupez.py re-invokes the same frozen
            # exe with `--role helper` under DUPEZ_ARCH=split. Without this
            # hiddenimport, PyInstaller doesn't see dupez_helper in dupez.py's
            # static graph (it's imported inside a runtime dispatch block)
            # and the spawned helper crashes with ModuleNotFoundError.
            "dupez_helper",
            "PyQt6.QtWidgets",
            "PyQt6.QtGui",
            "PyQt6.QtCore",
            "PyQt6.QtWebEngineWidgets",
            "PyQt6.QtWebEngineCore",
            "PyQt6.QtWebChannel",
            "PyQt6.QtNetwork",
            "pyqtgraph",
            "psutil",
            "keyboard",
            "PIL",
            "scapy",
            "scapy.all",
            "cryptography",
            "numpy",
            "pandas",
            "openpyxl",
            # Voice control (optional) — whisper/torch excluded below.
            "sounddevice",
            # GPC / CronusZEN (optional)
            "serial",
            "serial.tools",
            "serial.tools.list_ports",
            # Explorer COM trick used by map_host launcher
            "win32com",
            "win32com.client",
            "pythoncom",
            # mDNS hostname resolution — soft-imported by
            # app/network/enhanced_scanner.py::_mdns_lookup. Listed
            # here so PyInstaller bundles zeroconf + its submodules
            # into the frozen exe; without this, the scanner's 4th
            # stage silently falls through to the synthesized
            # fallback even when zeroconf is installed in dev.
            "zeroconf",
            "zeroconf._utils.ipaddress",
            "zeroconf._services.browser",
            "zeroconf._services.info",
        ]
    )


def _datas() -> list:
    return [
        (os.path.join(ROOT, "app", "config"), os.path.join("app", "config")),
        (os.path.join(ROOT, "app", "resources"), os.path.join("app", "resources")),
        (os.path.join(ROOT, "app", "assets"), os.path.join("app", "assets")),
        (os.path.join(ROOT, "app", "themes"), os.path.join("app", "themes")),
    ]


def _binaries() -> list:
    binaries = []
    firewall_dir = os.path.join(ROOT, "app", "firewall")
    if os.path.isdir(firewall_dir):
        for fname in os.listdir(firewall_dir):
            fpath = os.path.join(firewall_dir, fname)
            if fname.endswith((".dll", ".sys", ".exe")) and os.path.isfile(fpath):
                binaries.append((fpath, os.path.join("app", "firewall")))
    return binaries


def _excludes() -> list:
    return [
        # ML / heavy libs not used
        "tensorflow",
        "torch",
        "whisper",
        "openai-whisper",
        "matplotlib",
        "scipy",
        "Twisted",
        "stem",
        "PycURL",
        "pymongo",
        "redis",
        "logging-loki",
        "prometheus-client",
        # Dev tools
        "pytest",
        "black",
        "flake8",
        "mypy",
        "Sphinx",
        # Tcl/Tk — not used, pulls in _tcl_data/tzdata that fails
        "tkinter",
        "_tkinter",
        "tcl",
        # Other unused stdlib that drags in large data
        "test",
        "unittest",
        "pydoc",
    ]


def _upx_excludes() -> list:
    return [
        # Qt core DLLs — UPX corrupts these
        "Qt6Core.dll",
        "Qt6Gui.dll",
        "Qt6Widgets.dll",
        "Qt6Network.dll",
        "Qt6Svg.dll",
        "Qt6OpenGL.dll",
        # QtWebEngine — largest DLLs, most prone to corruption
        "Qt6WebEngineCore.dll",
        "Qt6WebEngineWidgets.dll",
        "Qt6WebChannel.dll",
        "QtWebEngineProcess.exe",
        # System / runtime
        "python3*.dll",
        "vcruntime*.dll",
        "msvcp*.dll",
        "ucrtbase.dll",
        "libcrypto*.dll",
        "libssl*.dll",
        # WinDivert driver — must not be compressed
        "WinDivert.dll",
        "WinDivert64.sys",
    ]


# ── Variant factory ────────────────────────────────────────────────

def build_variant(
    variant: str,
    exe_name: str,
    manifest_path: str,
    uac_admin: bool,
):
    """Run Analysis + PYZ + EXE for the named variant and return EXE.

    Writes ``_build_default.py`` before Analysis so the frozen exe
    has the right compiled-in arch default.
    """
    _write_build_default(variant)

    a = Analysis(
        [os.path.join(ROOT, "dupez.py")],
        pathex=[ROOT],
        binaries=_binaries(),
        datas=_datas(),
        hiddenimports=_hidden_imports(),
        hookspath=[],
        hooksconfig={},
        runtime_hooks=[],
        excludes=_excludes(),
        win_no_prefer_redirects=False,
        win_private_assemblies=False,
        cipher=BLOCK_CIPHER,
        noarchive=False,
    )

    # Strip tcl/tk timezone data that sneaks in via stdlib.
    a.datas = [
        d for d in a.datas
        if not d[0].startswith(("_tcl_data", "tcl", "tk"))
    ]

    pyz = PYZ(a.pure, a.zipped_data, cipher=BLOCK_CIPHER)

    exe = EXE(
        pyz,
        a.scripts,
        a.binaries,
        a.zipfiles,
        a.datas,
        [],
        name=exe_name,
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=True,
        upx_exclude=_upx_excludes(),
        runtime_tmpdir=None,
        console=False,
        disable_windowed_traceback=False,
        argv_emulation=False,
        target_arch=None,
        codesign_identity=None,
        entitlements_file=None,
        icon=os.path.join(ROOT, "app", "resources", "dupez.ico"),
        version=os.path.join(HERE, "version_info.py"),
        manifest=os.path.join(HERE, manifest_path),
        uac_admin=uac_admin,
    )
    return exe
